# Generated by Django 5.2 on 2025-04-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, verbose_name='Contact Number'),
            preserve_default=False,
        ),
    ]
