# Generated by Django 5.2 on 2025-04-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryagent_phone_number'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryagent',
            options={'ordering': ['-is_available', 'user__full_name'], 'verbose_name': 'Delivery Agent', 'verbose_name_plural': 'Delivery Agents'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
        ),
        migrations.AddField(
            model_name='pincode',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available Status'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='service_areas',
            field=models.ManyToManyField(related_name='agents', to='orders.pincode', verbose_name='Service Areas'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='orders.deliveryagent', verbose_name='Delivery Agent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Order Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Payment Failed')], default='pending', max_length=20, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Delivery Days'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
