# Generated by Django 5.2 on 2025-04-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_deliveryagent_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryagent',
            options={'ordering': ['-is_available', 'user__email'], 'verbose_name': 'Delivery Agent', 'verbose_name_plural': 'Delivery Agents'},
        ),
    ]
