# Generated by Django 5.2 on 2025-04-30 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_deliveryagent_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pincode',
            name='orders_pinc_code_f0b8d9_idx',
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Current Location'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available Status'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vehicle Number'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='orders.deliveryagent', verbose_name='Delivery Agent'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Delivery Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='cod_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='COD Advance Amount'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='Pincode'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Delivery Charge'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Delivery Days'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
