# Generated by Django 5.2 on 2025-05-01 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_deliveryagent_current_location_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Known Location'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available for Assignments'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Primary Contact Number'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='service_areas',
            field=models.ManyToManyField(related_name='agents', to='orders.pincode', verbose_name='Serviced Pincodes'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL, verbose_name='System Account'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vehicle Registration'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='orders.deliveryagent', verbose_name='Responsible Agent'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Delivery Instructions'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order', verbose_name='Assigned Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Complete Shipping Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razorpay Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order Total (Products + Delivery)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Parent Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price at Purchase'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product Variant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Purchased Quantity'),
        ),
    ]
