# Generated by Django 5.2 on 2025-05-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_feedback_comments_order_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, help_text='OTP for delivery confirmation', max_length=6, null=True, verbose_name='Delivery OTP'),
        ),
    ]
