# Generated by Django 5.2 on 2025-05-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_advance_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='COD Advance Payment Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_advance_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='COD Advance Required'),
        ),
    ]
