# Generated by Django 5.2 on 2025-05-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cod_advance_paid_at_order_cod_advance_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cod_advance_paid_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cod_advance_required',
        ),
    ]
