# Generated by Django 5.2 on 2025-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_cod_advance_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='required_cod_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Required COD Advance'),
        ),
    ]
