# Generated by Django 5.2 on 2025-05-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_required_cod_advance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='required_cod_advance',
        ),
    ]
