# Generated by Django 5.2 on 2025-05-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_required_cod_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Product Subtotal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Order Total'),
        ),
    ]
